services:
  neo4j-codescan:
    image: neo4j:5.26.0
    ports:
      - "${NEO4J_PORT_HTTP}:7474"
      - "${NEO4J_PORT_BOLT}:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_server_memory_pagecache_size=512m
    volumes:
      - neo4j_codescan_data:/data
      - neo4j_codescan_logs:/logs
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  neo4j_codescan_data:
  neo4j_codescan_logs:
